branches:
  only:
    - master
    - /^v.*$/

language: cpp

matrix:
  include:
    - os: linux
      script:
        - make -C libretro
    - os: osx
      script:
        - make -C libretro
    - os: windows
      before_script:
        - choco install make
      script:
        - make -C libretro platform=win
