branches:
  only:
    - master
    - /^v.*$/

language: cpp

services:
  - docker

matrix:
  include:
    - name: OSX x86_64
      os: osx
      script: make -C libretro -j4
    - name: Windows x86_64
      os: windows
      before_script: choco install make
      script: make -C libretro platform=win -j4
    - name: Linux x86_64
      script: make -C libretro -j4
    - name: Linux x86
      script:
        - docker pull dockcross/linux-x86
        - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp dockcross/linux-x86 make -C libretro -j4
    - name: Linux armv7
      script:
        - docker pull dockcross/linux-armv7
        - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp dockcross/linux-armv7 make -C libretro -j4
    - name: Linux arm64
      script:
        - docker pull dockcross/linux-arm64
        - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp dockcross/linux-arm64 make -C libretro -j4
    - name: Switch
      script:
        - docker pull devkitpro/devkita64
        - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp devkitpro/devkita64 make -C libretro platform=libnx -j4
    - name: Vita
      script:
        - docker pull malev/vita-toolchain
        - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp malev/vita-toolchain make -C libretro platform=vita -j4
    - name: GameCube
      script:
        - docker pull devkitpro/devkitppc
        - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp devkitpro/devkitppc make -C libretro platform=ngc -j4
    - name: Wii
      script:
        - docker pull devkitpro/devkitppc
        - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp devkitpro/devkitppc make -C libretro platform=wii -j4
    - name: Emscripten
      script: make -C libretro platform=emscripten -j4
    - name: Android arm
      script:
        - docker pull dockcross/android-arm
        - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp dockcross/android-arm make -C libretro platform=unix -j4
    - name: Android arm64
      script:
        - docker pull dockcross/android-arm64
        - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp dockcross/android-arm64 make -C libretro platform=unix-arm64 -j4

