branches:
  only:
    - master
    - /^v.*$/

language: cpp

services:
  - docker

matrix:
  include:
    - os: linux
      env:
        - ARCH=x86_64
      script:
        - make -C libretro
    - os: linux
      env:
        - PLATFORM=emscripten
      script:
        - make -C libretro platform=emscripten
    - os: linux
      env:
        - ARCH=x86
      script:
        - docker pull dockcross/linux-x86
        - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp dockcross/linux-x86 make -C libretro
    - os: linux
      env:
        - ARCH=armv7
      script:
        - docker pull dockcross/linux-armv7
        - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp dockcross/linux-armv7 make -C libretro
    - os: linux
      env:
        - PLATFORM=switch
      script:
        - docker pull devkitpro/devkita64
        - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp devkitpro/devkita64 make -C libretro platform=libnx
    - os: osx
      script:
        - make -C libretro
    - os: windows
      before_script:
        - choco install make
      script:
        - make -C libretro platform=win
