branches:
  only:
    - master
    - /^v.*$/

language: cpp

services:
  - docker

matrix:
  include:
    - os: linux
      script:
        - make -C libretro
    - os: linux
      script:
        - docker pull arm32v7/gcc
        - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp arm32v7/gcc /bin/sh -c "make -C libretro"
    - os: osx
      script:
        - make -C libretro
    - os: windows
      before_script:
        - choco install make
      script:
        - make -C libretro platform=win
