branches:
  only:
    - master
    - /^v.*$/

language: cpp

services:
  - docker

matrix:
  include:
    - os: linux
      script:
        - make -C libretro
    - os: linux
      script:
        - docker pull dockcross/linux-armv7
        - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp dockcross/linux-armv7 apt-get install make gcc make -C libretro
    - os: osx
      script:
        - make -C libretro
    - os: windows
      before_script:
        - choco install make
      script:
        - make -C libretro platform=win
